apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fastapi-latency-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    name: model-deployment
  minReplicaCount: 1
  maxReplicaCount: 30
  cooldownPeriod: 300
  triggers:
    - type: prometheus
      metadata: 
        serverAddress: http://prom-kube-prometheus-stackprometheus.monitoring.svc:9090
        metricName: fastapi_latency_p95
        query: | 
          histogram_quantile(0.95,sum(rate(http_request_duration_seconds_bucket[1m])) by (le))
        threshold: "0.1"  
    - type: cpu
      metricType: Utilization  # Allowed types are 'Utilization' or 'AverageValue'
      metadata:
        value: "50"